import Head from 'next/head';
import Image from 'next/image';
import homeStyles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className='w-screen h-screen flex justify-center items-center'>
      <Head>
        <title>Next, TS, TW, Redux Template</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='text-center p-24'>
        <h1 className='text-8xl font-bold'>
          <a href='https://nextjs.org' className='text-purple-500'>
            Next, TypeScript, Tailwind, Redux Toolkit
          </a>{' '}
          template
        </h1>
        <ul className='my-10 space-y-5'>
          <li className='text-3xl'>
            Update homepage at{' '}
            <code className={homeStyles.code}>pages/index.js</code>
          </li>
          <li className='text-3xl'>
            Add pages to <code className={homeStyles.code}>pages/...</code>
          </li>
          <li className='text-3xl'>
            Add redux slices to{' '}
            <code className={homeStyles.code}>features/...</code>
          </li>
        </ul>
        {/* <p className='my-10'>
        </p> */}
      </main>
    </div>
  );
}
