import Head from "next/head";
import Image from "next/image";
import homeStyles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="p-24 w-screen min-h-screen flex justify-center items-center bg-gray-100">
      <Head>
        <title>Next, TS, TW, Redux Template</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <h1 className="text-8xl font-bold">
          <span className="text-purple-500">NextJS Modern</span> Template
        </h1>
        <section className="flex flex-wrap justify-center items-baseline mt-10">
          <ul className="my-5 sm:my-10 space-y-5 bg-white p-20 rounded-xl sm:mr-10 text-left list-disc shadow-md">
            <li className="text-3xl">
              Update homepage at{" "}
              <code className={homeStyles.code}>pages/index.js</code>
            </li>
            <li className="text-3xl">
              Add pages to <code className={homeStyles.code}>pages/...</code>
            </li>
            <li className="text-3xl">
              Add redux slices to{" "}
              <code className={homeStyles.code}>redux/...</code>
            </li>
            <li className="text-3xl">
              Add tests to{" "}
              <code className={homeStyles.code}>__tests__/...</code>
            </li>
          </ul>
          <div className="my-5 sm:my-10 space-y-5 bg-white p-20 rounded-xl shadow-md">
            <h2 className="text-left text-4xl font-bold">Stack</h2>
            <ul className="text-left space-y-5 list-disc">
              <li className="text-3xl">NextJS</li>
              <li className="text-3xl">TailwindCSS</li>
              <li className="text-3xl">Typescript</li>
              <li className="text-3xl">Redux Toolkit</li>
              <li className="text-3xl">Jest & React Testing Library</li>
            </ul>
          </div>
        </section>
      </main>
    </div>
  );
}
