import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className='w-screen h-screen flex justify-center items-center'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='text-center'>
        <h1 className='text-5xl font-bold'>
          Welcome to this{' '}
          <a href='https://nextjs.org' className='text-blue-500'>
            Next, TypeScript, Tailwind, Redux Toolkit
          </a>{' '}
          template
        </h1>
        {/* <p>Start by adding new pages or redux slices</p> */}
      </main>
    </div>
  );
}
