import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to this{' '}
          <a href='https://nextjs.org'>
            Next, TypeScript, Tailwind, Redux Toolkit
          </a>{' '}
          template
        </h1>
        {/* <p>Start by adding new pages or redux slices</p> */}
      </main>
    </div>
  );
}
